// Auto-generated by deploy_wakeword.py — DO NOT EDIT MANUALLY
// Wake word: hi_jabra ('Hi Jabra')

#pragma once

#define WAKE_WORD_DISPLAY_NAME "Hi Jabra"
#define WAKE_WORD_THRESHOLD_X100 50
#define WAKE_WORD_WINDOW_SIZE 5
